apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: sonarqube
  name: sonarqube
spec:
  ports:
  - name: "9000"
    nodePort: 32341
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    io.kompose.service: sonarqube
  sessionAffinity: None
  type: LoadBalancer
